### ISSUE TITLE
是否可以加个图片组图？

### ISSUE THREAD

**Issue by chengzhongxue** [justice2001/halo-plugin-vditor#12]
更wp类似的多张图片组在一起
![image](https://github.com/justice2001/halo-plugin-vditor/assets/89380218/8731b43b-89ac-49d7-a7a7-d9b4025aea96)

**Comment by justice2001** [comment]
会下个大版本加入一个自定义块来实现图库功能。

**Comment by chengzhongxue** [comment]
![image](https://github.com/justice2001/halo-plugin-vditor/assets/89380218/1c767160-9ed5-46ed-bb40-fd68752a2de8)
