### ISSUE TITLE
echarts图表、mindmap脑图，在编辑器里面正常显示，但是发布后，在网页中无法显示

### ISSUE THREAD

**Issue by mutouloves** [justice2001/halo-plugin-vditor#13]
![3](https://github.com/justice2001/halo-plugin-vditor/assets/82205731/584d6178-7a7a-490d-bf9d-d5817c2b2808)
echarts图表、mindmap脑图，在编辑器里面正常显示，但是发布后，在网页中无法显示，请大佬看看
![1](https://github.com/justice2001/halo-plugin-vditor/assets/82205731/53d159cf-6dd6-45b8-80df-c77af1a940ad)
![2](https://github.com/justice2001/halo-plugin-vditor/assets/82205731/50516159-60ae-4c7d-a9b7-6963175d1e15)

**Comment by justice2001** [comment]
应该是个bug，下个版本一并修复

**Comment by mutouloves** [comment]
好的，感谢大佬的无私奉献
