### ISSUE TITLE
补充gallery文档及快捷插入

### ISSUE THREAD

**Issue by chengzhongxue** [justice2001/halo-plugin-vditor#15]

**Comment by justice2001** [comment]
不好意思哈，先看这个文档吧：https://github.com/justice2001/vditor-halo-render/blob/dev/doc/gallery.md

其他地方的文档还没补全。快捷按钮也还没放。

**Comment by chengzhongxue** [comment]
我想问一下，就是这样的语法，后面用户可以自己自定义？

**Comment by justice2001** [comment]
自定义语法不太好实现，现在这样的语法是在vditor源码上修改的，不太想对vditor有过大的改动。解析器是独立的一个项目：https://github.com/justice2001/vditor-halo-render。

现在有个方案就是给其他插件提供注入js和css的功能，其他插件用类似customElement的方法来实现即时渲染的能力。像这样：https://github.com/justice2001/halo-plugin-vditor/issues/11#issuecomment-1877062018

但也会引出一个问题就是vditor其实对HTML的渲染支持并不是非常的友好。暂时还没有想到更好的解决方案。

**Comment by justice2001** [comment]
> 我想问一下，就是这样的语法，后面用户可以自己自定义？

关于这个问题，需要再次回复下，Vditor上游最近已经提供了自定义解析的能力，下个版本开始应该会使用官方版本的vditor，不出意外的话，我会尝试在快捷插入的功能中加入自定义语法的能力。
