### ISSUE TITLE
版本1.5.0 无法编辑文章

### ISSUE THREAD

**Issue by MicroMatrixOrg** [justice2001/halo-plugin-vditor#16]
打开文章提示plugins/vditor-mde/assets/static/dist/js/i18n/zh_CN.js找不到

**Comment by justice2001** [comment]
我这没有成功复现这个问题，可以的话，您可以发下系统概览的内容（注意隐掉敏感信息），我排除下。

**Comment by MicroMatrixOrg** [comment]
> 我这没有成功复现这个问题，可以的话，您可以发下系统概览的内容（注意隐掉敏感信息），我排除下。

昨天无论新建还是编辑，只要切换到这个编辑器就提示上面的错误，今天我打开它又好了。可能是缓存的问题
