### ISSUE TITLE
更新插件之后代码块样式冲突

### ISSUE THREAD

**Issue by adozhao** [justice2001/halo-plugin-vditor#17]
更新最新版本后，代码块相关样式冲突~

![image](https://github.com/justice2001/halo-plugin-vditor/assets/23180747/742c6b1e-6412-481d-812f-7381eaf19da4)

以下为关闭插件后正常效果

![image](https://github.com/justice2001/halo-plugin-vditor/assets/23180747/0b6a679e-32dc-435e-b1ef-c51572364237)

站点查看地址：ado.zone

**Comment by justice2001** [comment]
谢谢反馈，这两天我发个版本修复
