### ISSUE TITLE
更新之后暗色模式异常

### ISSUE THREAD

**Issue by happyZYM** [justice2001/halo-plugin-vditor#18]
如图，刷新前
![屏幕截图 2024-01-16 011831](https://github.com/justice2001/halo-plugin-vditor/assets/33191271/fa64a1f1-f741-4bd7-9989-41a4dad89d77)
同一个页面刷新后变成
![屏幕截图 2024-01-16 011841](https://github.com/justice2001/halo-plugin-vditor/assets/33191271/d483a7ec-9f73-414c-9be1-f48cf30e2eba)

**Comment by happyZYM** [comment]
我试过了，1.4.0版本没有问题，更新到1.5.0版本后出问题的，我用的主题为Hao 1.4.6

**Comment by mutouloves** [comment]
![1](https://github.com/justice2001/halo-plugin-vditor/assets/82205731/a77e623b-e5d3-48a2-b881-6db1fb3a115d)
插件---Vditor编辑器---渲染---暗色模式修改后可以正常显示的，你可以试一下

**Comment by happyZYM** [comment]
@mutouloves 暗色模式的三种选项我都试过了，在我这边没用，不知道为啥

**Comment by justice2001** [comment]
这个确实是插件的bug，部分主题的样式被插件覆盖导致的的，正常来讲插件不应该覆盖这些颜色，这个问题已经修复完了.

如果想提前试试可以在这下载开发构建：https://git.mczhengyi.top/zhengyi/halo-plugin-vditor/actions/runs/60，但这个构建还没有完全测试完（已经接近尾声）.
