### ISSUE TITLE
编辑已发布文章的内容，只更改图片链接，不更改文章文字内容，点发布，提示发布成功，但实际不会保存新图片链接

### ISSUE THREAD

**Issue by mengtaixiao** [justice2001/halo-plugin-vditor#20]
系统信息
外部访问地址: https://blog.209902.xyz/
启动时间: 2024-01-17 01:35
版本: 2.11.3
构建时间: 2023-12-27 12:13
Git Commit: 8e9b07d
Java: IBM Semeru Runtime Open Edition / 17.0.9+9
数据库: H2 / 2.2.224
操作系统: Linux / 5.10.0-8-amd64
已激活主题: Dream
已启动插件:
Vditor编辑器
对象存储（Amazon S3 协议）
RSS
应用市场
搜索组件
Sitemap
评论组件
使用的哪种方式运行？
Docker Compose

在线站点地址
https://blog.209902.xyz/archives/1705491991649

发生了什么？
发现个BUG，Halo博客，Markdown编辑器（Vditor Markdown），编辑已发布文章的内容，只更改图片链接（更换图床，换新链接但图片还是那一张），不更改文章文字内容，点发布，提示发布成功，但实际不会保存新图片链接，再点编辑还是原来的图片链接，我还以为是CDN的问题，排查了半天才发现是Halo或者是Markdown编辑器的问题。

解决办法，更新图片链接的时候，也要更改文字内容，加个文字标点什么的都行（空格不行）。

在halo提了issue，他回复说是编辑器插件的问题，让我来这边提

相关日志输出
No response

附加信息
No response

**Comment by justice2001** [comment]
谢谢反馈，我去测试下

**Comment by justice2001** [comment]
确认问题所在了，所见即所得模式使用工具栏修改的数据并没有触发input事件，似乎是上游Vditor的问题，我去反馈并修复下。
