### ISSUE TITLE
关于行内公式渲染等问题

### ISSUE THREAD

**Issue by Einstein-schrodinger** [justice2001/halo-plugin-vditor#22]
1. 行内公式问题
数字以行内公式的形式呈现时需要在$符后额外再打一个空格才能渲染，例如$12$无法渲染，需要$ 12$才可以，这点是否有待改进？

2. 编辑器能否和主题一样使用自定义的字体

**Comment by justice2001** [comment]
1. 测试似乎为Vditor的问题，我会向vditor官方仓库进行反馈。
2. 可以考虑在后续添加一个字体的设置项。
