### ISSUE TITLE
“Tips” 样式会影响 Hao 主题其他页面样式

### ISSUE THREAD

**Issue by HenryZeng-Zero** [justice2001/halo-plugin-vditor#23]
使用了
<img width="550" alt="460998a61d4eff1865e76510a36a009" src="https://github.com/justice2001/halo-plugin-vditor/assets/36284614/316a4fbe-d041-4d35-8687-84817959edec">
<img width="500" alt="bdd1eeb28b7de40048e93d7c7f3bebb" src="https://github.com/justice2001/halo-plugin-vditor/assets/36284614/0abbeaec-8674-40b5-8f20-8eba3f9864ef">
<img width="591" alt="5b9ca19dbf614a25c711d7fd59e60fd" src="https://github.com/justice2001/halo-plugin-vditor/assets/36284614/bb829298-2186-4f1f-b394-92c83f537d05">

会干涉todo，moments的样式

如果开启：
<img width="275" alt="56885b1d12f9e65b962644f5dfcd58a" src="https://github.com/justice2001/halo-plugin-vditor/assets/36284614/8b06521b-ea54-4b1b-a11f-f50ec05b9c9e">
在浏览过markdown的页面后，因为已经进行了注入，也会影响todo，moments的样式

测速页面：https://developer-zeng.com/archives/1706092867029

故障排查：
+ 因为编辑器注入的全局样式没有使用前缀加以区分，导致css选择器选中了Hao主题的页面部件

**Comment by justice2001** [comment]
会在下个版本的render中修复，render将整合在1.6.0版本中

追踪: https://git.mczhengyi.top/zhengyi/halo-render/issues/10

**Comment by HenryZeng-Zero** [comment]
非常感谢
