### ISSUE TITLE
Halo Vditor 编辑器 更新到1.60后报错

### ISSUE THREAD

**Issue by OnlyCopi** [justice2001/halo-plugin-vditor#26]
/plugins/vditor-mde/assets/static/dist/js/i18n/zh_CN.js net::ERR_ABORTED 404 (Not Found)

**Comment by justice2001** [comment]
抱歉，最近比较忙，回复的有点晚。404的问题好像只在升级的时候会出现，触发条件暂时未知，复现之后再来看一下。

@bit15k 400的应该是独立的问题，和这个问题没有关系，一会我单开一个issue来处理。

**Comment by HowieHz** [comment]
仪表盘-快捷访问-刷新页面缓存 
可以试试，我刷新之后就好了
