### ISSUE TITLE
plantUML 无法渲染

### ISSUE THREAD

**Issue by Saoforest** [justice2001/halo-plugin-vditor#28]
<img width="872" alt="image" src="https://github.com/justice2001/halo-plugin-vditor/assets/46656157/2289ac55-6c92-45d1-9d69-9a9c4c4657d2">

<img width="962" alt="image" src="https://github.com/justice2001/halo-plugin-vditor/assets/46656157/a7f586bf-27cf-4a4f-a8e5-400777539eac">

**Comment by justice2001** [comment]
感谢反馈，问题会在下个版本修复
