### ISSUE TITLE
请问这个能去掉p标签？

### ISSUE THREAD

**Issue by chengzhongxue** [justice2001/halo-plugin-vditor#3]
![image](https://github.com/justice2001/halo-plugin-vditor/assets/89380218/c716da3a-d2d7-425f-a7de-17e2268c9bf0)
编译后
![image](https://github.com/justice2001/halo-plugin-vditor/assets/89380218/4c74733b-e020-42cb-9ea9-556b44e6e128)

**Comment by justice2001** [comment]
vditor渲染出来就是这样，在vditor渲染语法树里面，HTML块是包裹在一个段落里的，外面肯定会有一个p标签。方便问一下你想实现什么效果需要去除外面的p标签吗

**Comment by chengzhongxue** [comment]
https://moony.la/archives/1701790527174
![image](https://github.com/justice2001/halo-plugin-vditor/assets/89380218/9c68fdc6-324e-47f4-8303-ff131c6b7849)
原本标签因该是这样的
![image](https://github.com/justice2001/halo-plugin-vditor/assets/89380218/4d92eb02-0d66-4599-8512-65d36a2a7d49)
