### ISSUE TITLE
关于嵌入iframe等资源不能正常加载的问题

### ISSUE THREAD

**Issue by freedomgod** [justice2001/halo-plugin-vditor#31]
我尝试使用iframe来嵌入外部网页，或者其他音视频等资源，但是加载不了。是还不支持吗？或者我该如何实现这种需求。

**Comment by justice2001** [comment]
测试了下，能够正常嵌入的，可以提供下 markdown 的文本，我试一下。

<img width="875" alt="截屏2024-03-25 22 13 25" src="https://github.com/justice2001/halo-plugin-vditor/assets/28425753/85f63f27-b7fe-459c-ab84-f1cbf47a0959">

**Comment by freedomgod** [comment]
我也用其他链接试了下，可以正常显示。我的链接还不是https，而且还是IP地址，应该是这个原因了

> 测试了下，能够正常嵌入的，可以提供下 markdown 的文本，我试一下。
> 
> <img alt="截屏2024-03-25 22 13 25" width="875" src="https://private-user-images.githubusercontent.com/28425753/316529697-85f63f27-b7fe-459c-ab84-f1cbf47a0959.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNzczMzUsIm5iZiI6MTcxMTM3NzAzNSwicGF0aCI6Ii8yODQyNTc1My8zMTY1Mjk2OTctODVmNjNmMjctYjdmZS00NTljLWFiODQtZjFjYmY0N2EwOTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE0MzAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NTE4YTMxMjJjMWM0NzhkNTRhYjgxNGZkNGU3NjY4MzJlM2E4NjEwOTBlOTNhNTdlZjJhMjFhNTUyNmRjN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PvnYSJvYo5O_tqslNZh4UIhXhjysm9wfpBPm8EZj8m8">

我也用其他链接试了下，可以正常显示。我的链接还不是https，而且还是IP地址，应该是这个原因了

**Comment by justice2001** [comment]
如果你的网站是https的话应该就是这个问题了，iframe没法在https网站上嵌套http的资源。
