### ISSUE TITLE
多媒体无法正常渲染

### ISSUE THREAD

**Issue by HowieHz** [justice2001/halo-plugin-vditor#32]
![image](https://github.com/justice2001/halo-plugin-vditor/assets/94725606/bab6fba6-1134-460e-82cd-3a5c34c753a1)

![image](https://github.com/justice2001/halo-plugin-vditor/assets/94725606/e3fb16e3-67a1-4f6b-8950-c340a436cd0a)

![image](https://github.com/justice2001/halo-plugin-vditor/assets/94725606/45e81a28-dc80-418e-bf86-08c8c712c0ef)

测试页面：https://howiehz.top/archives/vditor-yang-shi-ce-shi#%E5%A4%9A%E5%AA%92%E4%BD%93

**Comment by HowieHz** [comment]
过去是能正常渲染的，大概三四个版本之前吧，后面没怎么注意，今天发现又不能渲染了

- 外部访问地址: https://howiehz.top
- 启动时间: 2024-03-17 10:56
- 版本: 2.13.1
- 构建时间: 2024-03-06 17:40
- Git Commit: 9473261
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MariaDB / 10.11.7-MariaDB-1:10.11.7+maria~ubu2204
- 操作系统: Linux / 6.1.0-rpi8-rpi-v8
- 已激活主题: [彼岸](https://github.com/guqing/halo-theme-higan)
- 已启动插件:
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [Metrics Graph](https://github.com/guqing/plugin-metrics-graph)
  - [Meilisearch](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [通知我](https://github.com/monyuan/notify-me)
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [Willow Markdown 编辑器](https://github.com/guqing/willow-mde)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

**Comment by HowieHz** [comment]
> Vditor 给的 Render 方法只能渲染链接的格式，之前版本不太确定，我找时间看一下。
> 
> 渲染示例:
> 
> ```
> [V](https://www.bilibili.com/video/BV1WH4y177MZ)
> ```
> 
> 这种格式的是可以渲染的。参见：https://ld246.com/article/1589813914768/comment/1710565574612

嗯，改为`[V](...)`了，稍微测试了一下

halo-plugin-vditor，`[V](...)`渲染，但直接丢链接不渲染
![image](https://github.com/justice2001/halo-plugin-vditor/assets/94725606/6c77ad41-8753-40ab-a45e-caa9d366976d)

当然实际文章渲染出来结果也是一致
![image](https://github.com/justice2001/halo-plugin-vditor/assets/94725606/a0c8d0af-2d67-4a47-bed2-f6816ecdda6c)


官方示例直接丢链接可以渲染：https://ld246.com/guide/markdown
![image](https://github.com/justice2001/halo-plugin-vditor/assets/94725606/eeaacdbd-e625-4dd3-b359-5ef1b818dcff)

**Comment by justice2001** [comment]
这个官方的示例不知道改了什么配置，它的项目自带的测试页面默认也没渲染，还在试是哪个选项导致的。

<img width="1009" alt="截屏2024-03-26 22 16 22" src="https://github.com/justice2001/halo-plugin-vditor/assets/28425753/b6a388ec-0746-4035-abe4-21363cc2cf49">
