### ISSUE TITLE
能否支持编辑时的 Title自动设置为文章的Title?

### ISSUE THREAD

**Issue by Dev-Wiki** [justice2001/halo-plugin-vditor#33]
新版的halo 默认编辑器支持插入标题并自动设置为文章标题, 咱这个编辑器是否也能支持?

**Comment by justice2001** [comment]
现在还在考虑如何实现，有时间就搞一下。

https://git.mczhengyi.top/zhengyi/halo-plugin-vditor/issues/74

**Comment by ruibaby** [comment]
> 使用第一个一级标题作为大标题

我觉得可行，但有几个问题：

1. 在最终正文中是否要包含这个标题。
2. 如何让用户知道可以这样做。
3. 在文章设置中修改标题之后如何同步到内容中。

**Comment by Dev-Wiki** [comment]
> > 使用第一个一级标题作为大标题
> 
> 我觉得可行，但有几个问题：
> 
> 1. 在最终正文中是否要包含这个标题。
> 2. 如何让用户知道可以这样做。
> 3. 在文章设置中修改标题之后如何同步到内容中。

可以对比测试一下，如果作为文章标题，页面标题已经显示了，内容里面就不要带这个标题了。

目前的编辑器版本会带到content里面，手动设置文章标题以后还会删除content里面的，可能是我个人习惯，不知道别人是否也是这个习惯。
或者可以增加一个开关设置是否包含到文章内容里面。

**Comment by justice2001** [comment]
> > 使用第一个一级标题作为大标题
> 
> 我觉得可行，但有几个问题：
> 
> 1. 在最终正文中是否要包含这个标题。
> 2. 如何让用户知道可以这样做。
> 3. 在文章设置中修改标题之后如何同步到内容中。

我的想法是在向halo提交内容的时候吧最上方的大标题去掉。 怎么让用户知道现在只能依靠更新日志和README了吧，后面再想想怎么搞。然后同步的问题倒是没想到，应该 watch 下 title 的变化去同步修改内容的大标题应该可以达到这个效果。

> > > 使用第一个一级标题作为大标题
> > 
> > 
> > 我觉得可行，但有几个问题：
> > 
> > 1. 在最终正文中是否要包含这个标题。
> > 2. 如何让用户知道可以这样做。
> > 3. 在文章设置中修改标题之后如何同步到内容中。
> 
> 可以对比测试一下，如果作为文章标题，页面标题已经显示了，内容里面就不要带这个标题了。
> 
> 目前的编辑器版本会带到content里面，手动设置文章标题以后还会删除content里面的，可能是我个人习惯，不知道别人是否也是这个习惯。 或者可以增加一个开关设置是否包含到文章内容里面。

我个人的习惯是第一个大标题作为文章标题，后面再出现一次的话感觉怪怪的。

**Comment by Dev-Wiki** [comment]
> > > 使用第一个一级标题作为大标题
> > 
> > 
> > 我觉得可行，但有几个问题：
> > 
> > 1. 在最终正文中是否要包含这个标题。
> > 2. 如何让用户知道可以这样做。
> > 3. 在文章设置中修改标题之后如何同步到内容中。
> 
> 我的想法是在向halo提交内容的时候吧最上方的大标题去掉。 怎么让用户知道现在只能依靠更新日志和README了吧，后面再想想怎么搞。然后同步的问题倒是没想到，应该 watch 下 title 的变化去同步修改内容的大标题应该可以达到这个效果。
> 
> > > > 使用第一个一级标题作为大标题
> > > 
> > > 
> > > 我觉得可行，但有几个问题：
> > > 
> > > 1. 在最终正文中是否要包含这个标题。
> > > 2. 如何让用户知道可以这样做。
> > > 3. 在文章设置中修改标题之后如何同步到内容中。
> > 
> > 
> > 可以对比测试一下，如果作为文章标题，页面标题已经显示了，内容里面就不要带这个标题了。
> > 目前的编辑器版本会带到content里面，手动设置文章标题以后还会删除content里面的，可能是我个人习惯，不知道别人是否也是这个习惯。 或者可以增加一个开关设置是否包含到文章内容里面。
> 
> 我个人的习惯是第一个大标题作为文章标题，后面再出现一次的话感觉怪怪的。

我也是如此, 目前插件一级标题是出现在内容里面的

![image](https://github.com/justice2001/halo-plugin-vditor/assets/12946956/06d308f7-bb63-404e-9ad4-9e9dbd14f97a)

新版的默认编辑器 大标题就是文章标题, 且不再包含到内容中了:
![image](https://github.com/justice2001/halo-plugin-vditor/assets/12946956/4c313bb1-3ad5-4c2d-a1fa-84a576043b49)

**Comment by ruibaby** [comment]
> > > 使用第一个一级标题作为大标题
> 
> > 
> 
> > 我觉得可行，但有几个问题：
> 
> > 
> 
> > 1. 在最终正文中是否要包含这个标题。
> 
> > 2. 如何让用户知道可以这样做。
> 
> > 3. 在文章设置中修改标题之后如何同步到内容中。
> 
> 
> 
> 我的想法是在向halo提交内容的时候吧最上方的大标题去掉。 怎么让用户知道现在只能依靠更新日志和README了吧，后面再想想怎么搞。然后同步的问题倒是没想到，应该 watch 下 title 的变化去同步修改内容的大标题应该可以达到这个效果。
> 
> 
> 
> > > > 使用第一个一级标题作为大标题
> 
> > > 
> 
> > > 
> 
> > > 我觉得可行，但有几个问题：
> 
> > > 
> 
> > > 1. 在最终正文中是否要包含这个标题。
> 
> > > 2. 如何让用户知道可以这样做。
> 
> > > 3. 在文章设置中修改标题之后如何同步到内容中。
> 
> > 
> 
> > 可以对比测试一下，如果作为文章标题，页面标题已经显示了，内容里面就不要带这个标题了。
> 
> > 
> 
> > 目前的编辑器版本会带到content里面，手动设置文章标题以后还会删除content里面的，可能是我个人习惯，不知道别人是否也是这个习惯。 或者可以增加一个开关设置是否包含到文章内容里面。
> 
> 
> 
> 我个人的习惯是第一个大标题作为文章标题，后面再出现一次的话感觉怪怪的。

需求明确就 OK 嗷。

至于如何让用户方便的知道，如果 vditor 可以扩展视图，那么可以考虑在第一个一级标题的旁边加个标志，或者在添加一级标题但还未输入文字的时候，在 placeholder 中提示。

有些时候文档当然要有，但如果在使用的时候就能让用户意识到这个功能可能会更好。

**Comment by Dev-Wiki** [comment]
> > > 标题的已经实现了，主题再等个两三天。
> > > 提交构建都在这，可以去试一下，应该可以用了：
> > > https://git.mczhengyi.top/zhengyi/halo-plugin-vditor/actions/runs/94
> > 
> > 
> > 我是了还是标题这个还是不行
> 
> 有去设置打开这个功能么，打开之后刷新，标题的位置会出现一个“T”

不是说标题不再内容中显示么? 我测试会显示在内容中:
![image](https://github.com/justice2001/halo-plugin-vditor/assets/12946956/b7ba356d-a03c-4fe5-b177-407975a8f2af)

**Comment by justice2001** [comment]
OK 我知道为啥了，今晚修一下吧

**Comment by Dev-Wiki** [comment]
> OK 我知道为啥了，今晚修一下吧

好的, 等出了新版我再测试一下

**Comment by Dev-Wiki** [comment]
测试了 最新的构建版本, 新建文章直接什么都不显示了...
![image](https://github.com/justice2001/halo-plugin-vditor/assets/12946956/b05deec7-63c5-439d-a4c3-c9eaff50403b)

**Comment by Dev-Wiki** [comment]
> 测试了 最新的构建版本, 新建文章直接什么都不显示了... ![image](https://private-user-images.githubusercontent.com/12946956/323108073-b05deec7-63c5-439d-a4c3-c9eaff50403b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMzY1MjAsIm5iZiI6MTcxMzMzNjIyMCwicGF0aCI6Ii8xMjk0Njk1Ni8zMjMxMDgwNzMtYjA1ZGVlYzctNjNjNS00MzlkLWE0YzMtYzllYWZmNTA0MDNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDA2NDM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3YmI0YzNhNmEyM2Q4NTY5MjQyODViZmZkZTgwZGJkMjIwNzYwMzQwOWExMzExMjc2ZjljY2YyMTBmZDcwMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RUJSF7mXL5rRVGXp9d1ko80733KazrztrA5Ins1nZpU)

![image](https://github.com/justice2001/halo-plugin-vditor/assets/12946956/6ef30e86-e9bd-42ee-82ef-cc423641ffaf)

**Comment by justice2001** [comment]
我这测试没问题的

**Comment by Dev-Wiki** [comment]
> 我这测试没问题的，可以打开F12看下有没有爆红，有爆红截张图可以。

![image](https://github.com/justice2001/halo-plugin-vditor/assets/12946956/5a02f88f-9615-42fd-a444-726f5a1ff5a5)

**Comment by justice2001** [comment]
测试了下 好像没有这问题

<img width="2047" alt="截屏2024-04-19 21 20 20" src="https://github.com/justice2001/halo-plugin-vditor/assets/28425753/c61d6494-ed37-4ddf-ab08-b20732443fc1">

**Comment by Dev-Wiki** [comment]
> 测试了下，好像没有这问题，要不就试试清下缓存或者重装插件🤦。
> 
> <img alt="截屏2024-04-19 21 20 20" width="2000" src="https://private-user-images.githubusercontent.com/28425753/323972586-c61d6494-ed37-4ddf-ab08-b20732443fc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NTA4NDYsIm5iZiI6MTcxMzc1MDU0NiwicGF0aCI6Ii8yODQyNTc1My8zMjM5NzI1ODYtYzYxZDY0OTQtZWQzNy00ZGRmLWFiMDgtYjIwNzMyNDQzZmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDAxNDkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2M2E4ZDdlYjU1ZTk5OGEzMDZjYjFlZTNjMTI1NWYxNzBhMDNmMjlmZjM1NjY2MWQ4MTlhZDJlNmQxZWMxMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6TYTFITbZ7KhnvJcGeCnuL3VVM-8990kHAsa9t-pSe4">

重新安装了一下确实好了

**Comment by holwell** [comment]
> > 使用第一个一级标题作为大标题
> 
> 我觉得可行，但有几个问题：
> 
> 1. 在最终正文中是否要包含这个标题。
> 2. 如何让用户知道可以这样做。
> 3. 在文章设置中修改标题之后如何同步到内容中。

我觉得不可行，本身标题在 halo 里面的设计就是 文章设置 中的一部分，它是一个独立的字段，也应该设计一个独立的输入位置，硬要为了这样一个不足，去割裂原来的设计，把一个独立的字段和正文文本里的一级标题糅杂到一起，搞什么提交时判断一级标题更新标题字段，编辑时又转换恢复成编辑器正文的一级标题，这种杂糅和冗余转换就是一个失败的方案。
总的来说，就是文章标题是 文章设置 的一个独立字段，编辑器就该只是文章正文的编辑器，两者不能杂糅在一起，这样的设计才不会有割裂感。
<img width="1278" alt="360截图18120417100114106" src="https://github.com/user-attachments/assets/bf39012d-2c2f-4492-98d1-1cae1dc447c6">

**Comment by justice2001** [comment]
> > > 使用第一个一级标题作为大标题
> > 
> > 
> > 我觉得可行，但有几个问题：
> > 
> > 1. 在最终正文中是否要包含这个标题。
> > 2. 如何让用户知道可以这样做。
> > 3. 在文章设置中修改标题之后如何同步到内容中。
> 
> 我觉得不可行，本身标题在 halo 里面的设计就是 文章设置 中的一部分，它是一个独立的字段，也应该设计一个独立的输入位置，硬要为了这样一个不足，去割裂原来的设计，把一个独立的字段和正文文本里的一级标题糅杂到一起，搞什么提交时判断一级标题更新标题字段，编辑时又转换恢复成编辑器正文的一级标题，这种杂糅和冗余转换就是一个失败的方案。 总的来说，就是文章标题是 文章设置 的一个独立字段，编辑器就该只是文章正文的编辑器，两者不能杂糅在一起，这样的设计才不会有割裂感。 <img alt="360截图18120417100114106" width="1278" src="https://private-user-images.githubusercontent.com/45387795/374029962-bf39012d-2c2f-4492-98d1-1cae1dc447c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyOTE2NDIsIm5iZiI6MTcyODI5MTM0MiwicGF0aCI6Ii80NTM4Nzc5NS8zNzQwMjk5NjItYmYzOTAxMmQtMmMyZi00NDkyLTk4ZDEtMWNhZTFkYzQ0N2M2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDA4NTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNTQ2NTQ2NzFiMjBmMzIwZDU4NzJhZGM0MzU0NDA1MWUzNDg2MWQ5YmQzMzlmZGYwMzg0YjYyOGFjODNlMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KQ6cJJPenkIVR2xJdkbWsLGmXlgWneyxNeFjJ0jxLY0">

感谢回复，最近我也感觉vditor插件现在的某些设计不太成熟（例如标题和前台渲染的问题），现在有一部分操作依赖于对渲染进行操作，可能会导致一定的性能问题。所以最近一段时间也在计划进行一些重构，对于标题问题现在暂时还没有比较合适的标题位置，如果您有合适的布局方案也欢迎提出来。
