### ISSUE TITLE
markdown解析异常

### ISSUE THREAD

**Issue by Dev-Wiki** [justice2001/halo-plugin-vditor#37]
粘贴下面内容到编辑器显示必然异常:
```markdown
- [ ]  1. 根证书是否齐全?

不同的颁发机构提供的数量不等,参见对应的官方网站

- [ ] 2. 根证书是否为最新?

根证书的更新要么联网系统自动更新, 要么手动安装更新.

- [ ] 3. 根证书颁发机构是否可信?

确定是否Windows系统对颁发机构信任

- [ ] 4. 客户端证书是否有效?

是否过期, 是否被吊销,等等.

- [ ] 5. 服务端证书是否有效?
```

![image](https://github.com/justice2001/halo-plugin-vditor/assets/12946956/0ab3b469-3991-4b34-8954-a93bb5918c75)

**Comment by Dev-Wiki** [comment]
![image](https://github.com/justice2001/halo-plugin-vditor/assets/12946956/ff495348-d763-4465-a6bd-ffd3f19db039)

**Comment by justice2001** [comment]
这个问题是 Vditor 解析的问题，不过这语法好像不规范吧（没见过这么写的）。

可以去 https://github.com/Vanessa219/vditor/issues 提交 ISSUE

**Comment by Dev-Wiki** [comment]
> 这个问题是 Vditor 解析的问题，不过这语法好像不规范吧（没见过这么写的）。
> 
> 可以去 https://github.com/Vanessa219/vditor/issues 提交 ISSUE

我知道了 就是复选框的写法：
```
- [ ] xxx
* [ ] xxx
```

- [ ] 这是使用 -
* [ ] 这是使用 *
