### ISSUE TITLE
各语言代码块中的字体颜色和背景色对比度不明显，字体看不清楚

### ISSUE THREAD

**Issue by funtime1** [justice2001/halo-plugin-vditor#38]
关闭`编辑器代码块渲染`的情况下，代码块语言（比如python）的字体和背景色都是浅灰色，导致字体看不清楚。 

![image](https://github.com/justice2001/halo-plugin-vditor/assets/90565575/5b1b58a8-f4aa-4648-9c48-c5007827d2e9)

当鼠标点击代码块的时候，字体是黑色的，能看清楚，没问题。
![image](https://github.com/justice2001/halo-plugin-vditor/assets/90565575/25820909-5e89-4ff2-bd6d-2cef12bf6d76)

因此，我想修改下代码块中字体的颜色，该怎么修改呢。

**Comment by justice2001** [comment]
这个我也发现了，我最近处理一下吧，刚好最近把事忙完了。

**Comment by justice2001** [comment]
确认问题应该是和 Docsme 的兼容性问题，Docsme 把样式覆盖导致的，这两天修复一下。
