### ISSUE TITLE
使用一键导入md，使用插件halo-plugin-vditor编辑器插件，图片显示异常

### ISSUE THREAD

**Issue by GordonChanFZ** [justice2001/halo-plugin-vditor#4]
图床使用onedrive，图片链接：
<img src="https://3zp8hm-my.sharepoint.com/personal/gordonchan365_3zp8hm_onmicrosoft_com/_layouts/52/download.aspx?share=EaQV99gBm5RJmA30dt-gF8QB_wUrNHgCXdJY66UCt4VT1Q" alt="fink-on-k8s.assets/v2-ae0fbd30ffbc9b64d5e0aaff298e92c5_r.jpg" title="v2-ae0fbd30ffbc9b64d5e0aaff298e92c5_r.jpg">
使用插件一键上传md，在未发布中编辑器选vditor，不管是预览还是发布后在网站浏览图片都不能展示，刷新搜索引擎和缓存，直接访问ip地址，都试过了，使用ByMd可以。
halo版本：2.11.1
插件版本：1.2.0

**Comment by justice2001** [comment]
请提供下您上传md插件的名称。上面的图片被github匿名化了，您可以直接发一下原始链接。我试一下。

**Comment by justice2001** [comment]
我测试了`文章导入导出`和`VSCode拓展`上传都没有复现问题。
<img width="1763" alt="截屏2023-12-09 11 08 35" src="https://github.com/justice2001/halo-plugin-vditor/assets/28425753/b03ba7da-1d00-449f-9ea0-0203008a98a4">

**Comment by GordonChanFZ** [comment]
> 请提供下您上传md插件的名称

本地使用的Typora编辑器，md直接使用一键上传,编辑器是ByteMD
![image](https://github.com/justice2001/halo-plugin-vditor/assets/77518307/2a577c2d-f7b3-4ebf-8cee-01f6eba8a1c5),
图片的原始链接："https://3zp8hm-my.sharepoint.com/personal/gordonchan365_3zp8hm_onmicrosoft_com/_layouts/52/download.aspx?share=EaQV99gBm5RJmA30dt-gF8QB_wUrNHgCXdJY66UCt4VT1Q" 

问题我验证出来了，我使用的图片引用方式是html格式的：
<=去掉=img src="https://3zp8hm-my.sharepoint.com/personal/gordonchan365_3zp8hm_onmicrosoft_com/_layouts/52/download.aspx?share=EfoOTVKCRJNKs1MbPwPv3iEBF1L2JrDCq-VRfDevwglmoA" alt="test.assets/image-20231208044738486.png" title="image-20231208044738486.png">

如果采用这种格式就可以==![]=去掉=(https://3zp8hm-my.sharepoint.com/personal/gordonchan365_3zp8hm_onmicrosoft_com/_layouts/52/download.aspx?share=EfoOTVKCRJNKs1MbPwPv3iEBF1L2JrDCq-VRfDevwglmoA)"==

**Comment by justice2001** [comment]
OK我测试下

**Comment by justice2001** [comment]
怪了，我这测试都能正常显示，后续我关注下这个问题吧。
<img width="1765" alt="截屏2023-12-09 22 31 55" src="https://github.com/justice2001/halo-plugin-vditor/assets/28425753/305125f2-761e-4a52-9297-228a9f7a2b47">
