### ISSUE TITLE
编辑器切换功能

### ISSUE THREAD

**Issue by wxyShine** [justice2001/halo-plugin-vditor#40]
![image](https://github.com/justice2001/halo-plugin-vditor/assets/42802152/067bb7c3-533b-401a-a090-7a61c3468d9c)
会支持历史文章编辑时 切换为默认编辑器吗？

**Comment by justice2001** [comment]
这个是 Halo 本身的限制。因为默认编辑器和 Vditor 格式不同，默认编辑器是基于 HTML 的富文本，Vditor 是 Markdown，所以没法切换。

**Comment by wxyShine** [comment]
上次群里问的 说是需要插件去支持🤣

**Comment by justice2001** [comment]
啊 这样吗，找时间去看一下怎么个事🤣

**Comment by ruibaby** [comment]
> 上次群里问的 说是需要插件去支持🤣

建议是做一个专门用于格式转换的插件，而不是让编辑器来做这件事，毕竟没有什么经常需要格式转换的需求，也不是常规用法。

**Comment by wxyShine** [comment]
> > 上次群里问的 说是需要插件去支持🤣
> 
> 建议是做一个专门用于格式转换的插件，而不是让编辑器来做这件事，毕竟没有什么经常需要格式转换的需求，也不是常规用法。

原来是这样啊
