### ISSUE TITLE
咨询一下如何同步github的 issue和 发布到gitea的?

### ISSUE THREAD

**Issue by Dev-Wiki** [justice2001/halo-plugin-vditor#42]
如题, 麻烦咨询一下~

**Comment by justice2001** [comment]
之前随便搓的一个工具，用Github Hook + Gitea的API实现的。仓库在这：https://git.mczhengyi.top/zhengyi/git-sync-bot/src/branch/bot-1.0，不太好配置，想改个新版的也一直没啥时间。

**Comment by Dev-Wiki** [comment]
> 之前随便搓的一个工具，用Github Hook + Gitea的API实现的。仓库在这：https://git.mczhengyi.top/zhengyi/git-sync-bot/src/branch/bot-1.0，不太好配置，想改个新版的也一直没啥时间。

也支持 同步 Release么? 我可以手动 gitea同步 github, 但是 Release同步不过来, 设置gitea同步的时候选择了工单好像还是不行

**Comment by justice2001** [comment]
我这个工具还不行，但用api应该可以实现

**Comment by Dev-Wiki** [comment]
> 我这个工具还不行，但用api应该可以实现

非常感谢~
