### ISSUE TITLE
个人中心的文章编辑器，插入图片无法打开

### ISSUE THREAD

**Issue by chengzhongxue** [justice2001/halo-plugin-vditor#44]
![image](https://github.com/user-attachments/assets/fbc12cd7-6415-4a02-bf87-14f982d18589)
你可以测试下

**Comment by justice2001** [comment]
确实有点问题

**Comment by chengzhongxue** [comment]
什么问题，我写的也遇到这样的问题了，然后我试了下你的发现也是这样

**Comment by justice2001** [comment]
现在暂时只是看到个人中心里的编辑器，附件上传的组件没渲染出来，具体的再看看
<img width="411" alt="截屏2024-07-25 15 06 10" src="https://github.com/user-attachments/assets/56268e36-0cfe-4bad-8e66-656102937e52">

**Comment by justice2001** [comment]
找到问题所在了，这个应该是halo的bug，uc因为没有附件管理菜单，uc在注册插件的时侯没有注册附件管理的插件，导致AttachmentSelectorModal组件没有注册到全局组件中。所以这个会出现没有加载组件的问题。一会我去halo那边提个issue吧

**Comment by chengzhongxue** [comment]
但是我发现了个很奇怪的问题，文章里面的可以打开，然后瞬间的也不能打开

**Comment by chengzhongxue** [comment]
我知道了，文章是halo里面的所以就可以
![image](https://github.com/user-attachments/assets/ca1e26d4-b52b-4dad-bea7-74382bed9eb9)

**Comment by justice2001** [comment]
https://github.com/halo-dev/halo/issues/5278 找到了这个issue

**Comment by chengzhongxue** [comment]
我还提过这个问题，我都忘记了，哈哈哈

**Comment by justice2001** [comment]
真是，我都没注意到
