### ISSUE TITLE
修改文字的时候页面上下跳动

### ISSUE THREAD

**Issue by simanya2** [justice2001/halo-plugin-vditor#45]
删除键盘：有时删除一行文字，按一次删除键，页面就跳动一次，多点几次，就找不到找不到这一行文字了；
添加文字：当把这一行文字，删掉一部分，再次在这一行输入文字，输入一次，页面就往下滚动一次；

**Comment by justice2001** [comment]
这个问题我这里没有成功复现，这个问题触发频率很高吗
