### ISSUE TITLE
粘贴图片，会不再指定位置

### ISSUE THREAD

**Issue by simanya2** [justice2001/halo-plugin-vditor#46]
前提，文章上下都有内容：
1.当在光标在某个位置闪烁的时候，粘贴图片，图片不再光标的位置，是在光标往上的位置，如果光标所在位置的上面有文本，图片会在文本的上面，把图片删除，点击插入图片，可以插入到光标的位置；
2.当在光标在某个位置闪烁的时候，粘贴图片，有时候粘贴就找不到图片，不知道粘贴到哪里去了，但是附件里面有，点击插入图片，可也以插入到光标的位置；；

**Comment by justice2001** [comment]
问题记录：

1. 在文本中进行粘贴会粘到文本上一行，在单段粘贴没有问题
2. 暂未复现
