### ISSUE TITLE
文章内容多，编辑器会卡

### ISSUE THREAD

**Issue by simanya2** [justice2001/halo-plugin-vditor#47]
文章里有五万多字，里面也有图片，当再次编辑的时候，在编辑器里面就会很卡，不知道是哪里的原因，正常浏览文章加载速度很快

**Comment by justice2001** [comment]
编辑器卡的问题，你可以试一下吧文章粘到这个网址里试一下 https://ld246.com/guide/markdown ，如果也会卡，说明是编辑器的优化问题，和这个插件关系就不太大了。我试一下能不能优化下。

**Comment by simanya2** [comment]
贴进去是没有图片的，会卡，反应好慢，如果带有图片，会更卡
