### ISSUE TITLE
章节自动编号

### ISSUE THREAD

**Issue by zhangfenghui** [justice2001/halo-plugin-vditor#48]
大佬好， 我想在你的插件基础上实现章节自动编号功能，但是没有找到好的入手点，可以给点提示吗？
例如:
markdown这样写
```
# H1
## H2
## H2
# H1
## H2
### H3
#### H4
##### H5
```
渲染出来的结果
```
1. H1
1.1. H2
1.2. H2
2. H1
2.1. H2
2.1.1. H3
2.1.1.1. H4
2.1.1.1.1. H5
```

**Comment by justice2001** [comment]
方法倒是很多种，如果想直接修改这个插件实现的话，可以看下下面：

修改渲染结果应该可以参考下这个：https://ld246.com/article/1588412297062 ，或者也可以在保存前对渲染的html进行处理，蕾丝这种处理：https://github.com/justice2001/halo-plugin-vditor/blob/a3d2843eb46b0d0133281908b2473022d7bdef40/console/src/utils/vditor-utils.ts#L240-L257

编号的话需要自己获取html/markdown来解析出标题结构，或者通过exportJson来获取语法树，然后据此完成编号。

前台渲染实现的话就比较简单了，用css或js修改应该都能做到。

**Comment by ruibaby** [comment]
不推荐去显示这些 “黑魔法”，OP 需要的应该是一个 TOC 生成，而不是直接去改 heading 的渲染结果。

**Comment by zhangfenghui** [comment]
我需要的就是可以自动对章节编号的功能，每次更新文档，随便删点章节，没编号条例不清晰，改编号能吐血

**Comment by justice2001** [comment]
好像可以用css计数器可以实现

```
body {
    counter-reset: h1; /* 初始化h1计数器 */
}

h1 {
    counter-reset: h2; /* 初始化h2计数器 */
}

h2 {
    counter-reset: h3; /* 初始化h3计数器 */
}

h1::before {
    counter-increment: h1;
    content: counter(h1) ". ";
    font-weight: bold;
}

h2::before {
    counter-increment: h2;
    content: counter(h1) "." counter(h2) " ";
    font-weight: bold;
}

h3::before {
    counter-increment: h3;
    content: counter(h1) "." counter(h2) "." counter(h3) " ";
    font-weight: bold;
}
```
