### ISSUE TITLE
插入代码块，会出现下面问题

### ISSUE THREAD

**Issue by simanya2** [justice2001/halo-plugin-vditor#49]
![P_2024-07-31_10-37-45](https://github.com/user-attachments/assets/1ae786b2-7735-411c-80de-d3d8ef3f416e)
![P_2024-07-31_10-37-14](https://github.com/user-attachments/assets/67720fa6-5e7b-4d63-b0e9-56679fee3752)

**Comment by justice2001** [comment]
是点击插入代码块的按钮触发的问题吧，应该是vditor的bug，在加粗文本后方创建代码块会出现创建失败的问题，然后自动跳到行首，再次点击会在上面创建代码块。

**Comment by simanya2** [comment]
在不加粗的情况下是没问题的，好神奇
