### ISSUE TITLE
插件昨晚开始后台不显示了。

### ISSUE THREAD

**Issue by MGM-LOL** [justice2001/halo-plugin-vditor#5]
![screenshot20231218](https://github.com/justice2001/halo-plugin-vditor/assets/154243807/92dd5660-d1ec-484f-a29b-8ffdc9d8cc2c)

我中间重装过，还是后台不显示。是出BUG了嘛

**Comment by justice2001** [comment]
没理解你的意思，我看你截图是正常显示的啊，具体是什么不显示呢

**Comment by ruibaby** [comment]
看描述似乎和 Vditor 使用了 unpkg.com 的 CDN 有关。目前 unpkg.com 在中国大陆似乎很难访问到。

<img width="1396" alt="图片" src="https://github.com/justice2001/halo-plugin-vditor/assets/21301288/aff9f2c5-5f7c-45b5-864a-60a07283ef01">

**Comment by justice2001** [comment]
嗯，下个版本我会把所有的库都搬到本地访问，原始项目好像就提供了一个unpkg的cdn。

**Comment by justice2001** [comment]
link https://git.mczhengyi.top/zhengyi/halo-plugin-vditor/issues/5

**Comment by MGM-LOL** [comment]
> 没理解你的意思，我看你截图是正常显示的啊，具体是什么不显示呢

傻了，我截图的时候明明是内容那里是空白的。现在好了，
