### ISSUE TITLE
标题号能隐藏掉吗

### ISSUE THREAD

**Issue by yangshifei** [justice2001/halo-plugin-vditor#50]
![image](https://github.com/user-attachments/assets/885fe085-d5a7-416e-bcfd-666c03c16aac)

**Comment by justice2001** [comment]
这个应该不是vditor渲出来的结果吧，您用的是什么主题呢

**Comment by yangshifei** [comment]
![image](https://github.com/user-attachments/assets/6a6519a6-c2b1-4200-9130-0012ce1e2047)
这个主题

**Comment by justice2001** [comment]
这个是主题带的，关闭方法：主题设置-文章-启用文章标题图标（禁用）

**Comment by yangshifei** [comment]
> 这个是主题带的，关闭方法：主题设置-文章-启用文章标题图标（禁用）

嗯嗯，看到了谢谢
