### ISSUE TITLE
在编辑器内使用`文字`时，文章发布后不会将这视为一个代码块而是直接显示\`文字`，不知道我这样说您能不能理解

### ISSUE THREAD

**Issue by PLA-cjh** [justice2001/halo-plugin-vditor#52]
![1723557647187](https://github.com/user-attachments/assets/6799fa3c-74cd-4680-b650-5217ec51f62b)
然后在编辑器内看着是正常的
![1723557737120](https://github.com/user-attachments/assets/6459b68b-572b-4624-8a4d-e9af3bf840f2)

**Comment by justice2001** [comment]
你用的应该是earth这个默认主题，这个主题就是这么设计的

**Comment by ruibaby** [comment]
使用最新版本的 Earth，可以在主题设置里选择其他渲染样式。

https://github.com/halo-dev/theme-earth/pull/132

**Comment by PLA-cjh** [comment]
感谢


| |
陈佳浩
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Ryan ***@***.***> |
| 发送日期 | 2024年8月14日 10:28 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [justice2001/halo-plugin-vditor] 在编辑器内使用`文字`时，文章发布后不会将这视为一个代码块而是直接显示\`文字`，不知道我这样说您能不能理解 (Issue #52) |

使用最新版本的 Earth，可以在主题设置里选择其他渲染样式。

halo-dev/theme-earth#132
