### ISSUE TITLE
复制文章图片加载不了

### ISSUE THREAD

**Issue by yushuiguozhi** [justice2001/halo-plugin-vditor#54]
![微信截图_20240914135701](https://github.com/user-attachments/assets/81ec1d8f-4048-44f9-9b0e-3bf5c4bfaa3f)
这个从cdds 复制，不知道从其他地方复制是不是和这个问题

**Comment by justice2001** [comment]
<img width="664" alt="截屏2024-09-15 00 13 55" src="https://github.com/user-attachments/assets/2dc690c9-9750-48f4-85c2-0a9ac1145439">

额，cdds是啥，我搜到这个，不知道是不是，这个网站的链接都是http协议的，如果你的站点时https的，chrome就会把这个链接换成https，cdds服务器https没有这个资源，所以加载不出来；

建议把图片下载下来手动传到halo的文章里，不用外链。
