### ISSUE TITLE
在Halo市场无法安装插件

### ISSUE THREAD

**Issue by majinshan** [justice2001/halo-plugin-vditor#55]
在应用市场安装插件报错：**服务器内部发生错误，请稍候再试。**
Halo版本 2.19

Halo日志：

2024-09-28T12:45:18.835+08:00 ERROR 7 --- [reactor-http-epoll-2] a.w.r.e.AbstractErrorWebExceptionHandler : [eedc6d55-61887]  500 Server Error for HTTP POST "/apis/api.console.halo.run/v1alpha1/plugins/-/install-from-uri"

org.springframework.web.reactive.function.client.WebClientRequestException: Failed to resolve 'halo-store-assets.031150231bf47fe490654f9e3d11f01d.r2.cloudflarestorage.com' [A(1)]
	at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:136) ~[spring-webflux-6.1.12.jar:6.1.12]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
	*__checkpoint ⇢ Request to GET https://halo-store-assets.031150231bf47fe490654f9e3d11f01d.r2.cloudflarestorage.com/vditor-mde-1.8.0.jar [DefaultWebClient]
	*__checkpoint ⇢ run.halo.app.security.InitializeRedirectionWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ run.halo.app.security.device.DeviceSessionFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ SecurityWebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ AuthorizationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ExceptionTranslationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ LogoutWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ServerRequestCacheWebFilter [DefaultWebFilterChain]

**Comment by justice2001** [comment]
看起来像是应用商店在下载插件的时候遇到了网络问题，建议检查下网络
