### ISSUE TITLE
功能建议：保留编辑模式

### ISSUE THREAD

**Issue by holwell** [justice2001/halo-plugin-vditor#57]
假如我的编辑模式习惯第二个“即时渲染”，那么我就希望下次使用编辑器的时候，仍然是默认这个模式，就不用重新选择了，我觉得这个还挺刚需的。

**Comment by justice2001** [comment]
这个默认模式可以在插件设置里更改的

**Comment by holwell** [comment]
好的，看到了，谢谢作者๑•́₃•̀๑



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月11日(周五) 晚上11:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [justice2001/halo-plugin-vditor] 功能建议：保留编辑模式 (Issue #57)




 
这个默认模式可以在插件设置里更改的
