### ISSUE TITLE
无法打开历史文章编辑

### ISSUE THREAD

**Issue by wxyShine** [justice2001/halo-plugin-vditor#6]
![image](https://github.com/justice2001/halo-plugin-vditor/assets/42802152/834aa815-aff6-4fb5-b6c3-8915454345bf)
![image](https://github.com/justice2001/halo-plugin-vditor/assets/42802152/b1d421c4-4d6a-4daa-8d66-1a675c1eb33f)
![image](https://github.com/justice2001/halo-plugin-vditor/assets/42802152/961cb569-39e8-4f03-8016-d43d7498791b)

使用vditor无法编辑历史文章， 使用其他md编辑器正常打开编辑

**Comment by wxyShine** [comment]
halo 版本
[2.11.2](https://github.com/halo-dev/halo/releases/tag/v2.11.2)


名称
Vditor编辑器
描述
适用于Halo的Vditor编辑器
版本
1.2.0

**Comment by justice2001** [comment]
应该是编辑器没加载成功资源导致的，资源cdn服务器在国外，访问不太顺畅，下个版本会把资源全放到本地.

link https://github.com/justice2001/halo-plugin-vditor/issues/5
link https://git.mczhengyi.top/zhengyi/halo-plugin-vditor/issues/5
