### ISSUE TITLE
开启插件导致样式冲突问题

### ISSUE THREAD

**Issue by github-ado** [justice2001/halo-plugin-vditor#7]
#### 开启前
![image](https://github.com/justice2001/halo-plugin-vditor/assets/23180747/bcf3cff3-119a-4a9d-9318-722d7990da1e)

#### 开启后
![image](https://github.com/justice2001/halo-plugin-vditor/assets/23180747/b88d34cd-8ae0-4ac4-b54d-cbcf6607f6ab)

**Comment by github-ado** [comment]
这个插件非常中意，如果能够halo官方参与维护就好了，如果成为halo默认编辑器更好，给作者赞一个👍

**Comment by ruibaby** [comment]
> 这个插件非常中意，如果能够halo官方参与维护就好了，如果成为halo默认编辑器更好，给作者赞一个👍

Halo 的生态发展是需要靠各位优秀的社区开发者的，不是说 Halo 官方参与进来就会更好，我们最需要做的就是完善好开发文档和开发体验。

当然，我个人同样作为社区开发者，如果有需要协助的地方我也会参与进来。

感谢支持。

**Comment by justice2001** [comment]
谢谢支持，这个问题会在下个版本修复 :heart:

**Comment by github-ado** [comment]
我有个小小提议不知道是否合理，就是把Halo默认编辑器也作为可插拔的插件 🌹🌹🌹 @ruibaby

**Comment by ruibaby** [comment]
> 我有个小小提议不知道是否合理 🌹🌹🌹，大概也了解halo的用意，毕竟编辑器是面向大众的，而不只是面向程序员的，但对于很多”洁癖“的程序员来说，默认的编辑器一直启用而不去使用的话总感觉冗余，所以建议把Halo默认编辑器也作为可插拔的插件 当没有安装任何编辑器时候，在界面上提供安装编辑器插件的入口就行 @ruibaby

把默认编辑器作为预设插件是可行的，但目前默认编辑器和后台有点耦合，而且我担心作为插件之后很多地方会受限。

可以考虑在 Halo 提交一个 issue 记录一下。

**Comment by justice2001** [comment]
好像出现了个很影响体验的bug，稍等修复
