### ISSUE TITLE
与Halo界面样式适配问题

### ISSUE THREAD

**Issue by github-ado** [justice2001/halo-plugin-vditor#8]
开启插件后，应用vditor编辑器，鼠标放在右边区域滑动鼠标滚轮出现滚动条，哪怕没有键入任何内容
![image](https://github.com/justice2001/halo-plugin-vditor/assets/23180747/8550b29c-916a-4324-bb0f-dcda439eece9)

**Comment by justice2001** [comment]
感谢反馈，Bug将在v1.3.1修复
